<h1>Inscription</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('usr_email'))."<br>";
echo $this->formRow($form->get('usr_password'))."<br>";
echo $this->formRow($form->get('usr_password_confirm'))."<br>";
echo $this->formRow($form->get('captcha'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>