
<h1>Comments index</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('comments/default', array('controller' => 'Index', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('value'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
 ?>


 <h1>Index = Retrieve</h1>

<table>
<tr>
	<th>id</th>
	<th>value</th>
</tr>
<?php
	//foreach ($rowset as $row) {
?>
		<tr>
			<td><?php // echo $row['id']; ?></td>
			<td><?php  //echo $row['value']; ?></td>
		</tr>
			
<?php
	//}
?>
</table> 
 
