<h1>Login </h1>
<?php echo $this->escapeHtml($this->messages); ?>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('usr_email'))."</br>";
	echo $this->formRow($form->get('usr_password'))."<br></br>";
	echo $this->formRow($form->get('rememberme'))."</br>";
	echo $this->formSubmit($form->get('submit'))."<br></br>";
	echo $this->form()->closeTag();
?>
<?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' ."<b>". $this->escapeHtml($user->usr_email)."</b>";
?>		
 | 	
 	<a href="<?php //echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'index'))?>">
    <?php //echo $this->translate('admin') ?></a>

 	<a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>">
   <?php echo $this->translate('Logout'); ?></a> 
<?php
    } else {
        echo 'Not logged in';
   
?>
<p>
	<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 
		'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |  
	<a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>
<?php  } ?>