<?php
echo '<h1>Create</h1>';
// $form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('auth/default', array('controller' => 'admin', 'action' => 'create'))); 

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);

echo $this->formRow($form->get('usr_password'))."</br>";
echo $this->formRow($form->get('usr_email'))."</br>";
echo $this->formRow($form->get('usrl_id'))."</br>";
echo $this->formRow($form->get('lng_id'))."</br>";
echo $this->formRow($form->get('usr_active'))."</br>";
echo $this->formSubmit($form->get('submit'))."<br></br>";

echo $this->form()->closeTag();