<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/lamia.css"
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


 
 <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">

 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Kwaret</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Gérer les formulaires reçus</a></li>
      <li><a href="#">Gérer les comptes utilisateurs</a></li> 
    </ul>
  </div>
</nav>
 </div>
</nav>
  <ul class="nav navbar-nav navbar-right">
      <li><p>Bienvenue @admin</p></li>
      
    </ul>

        <div class="row" >
        <br>
        </br>
        </div>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Email</th>
      <th>Date inscription</th>
      <th>Traitement/Validation</th>
     
    </tr>
  </thead>
  <tbody>

    <tr>
      <th scope="row">1</th>
      <td>@email 1</td>
      <td>@date</td>
      <td>Validé</td>

    </tr>
    <tr>
      <th scope="row">2</th>
      <td>@email 2</td>
      <td>@date</td>
      <td>En cours</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>@email 3</td>
      <td>@date</td>
      <td>En cours</td>
    </tr>
 
 
  </tbody>
</table>
</body>
<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>
</html>










<!-- <h1>Index</h1>
<a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'create')); ?>">Create</a>
<table>
<tr>
  <th>usr_id</th>
  <th>usr_email</th>
</tr>
<?php
  foreach ($rowset as $row) {
?>
    <tr>
      <td><?php  echo $row['usr_id']; ?></td>
      <td><?php  echo $row['usr_email']; ?></td>
      <td><a href="<?php echo $this->url('auth/default', 
        array('controller' => 'admin', 'action' => 'update', 'id' => $row['usr_id'])); ?>">Edit</a></td>
      <td><a href="<?php echo $this->url('auth/default',
        array('controller' => 'admin', 'action' => 'delete', 'id' => $row['usr_id']));?>" onclick="return confirm('Do you rely want to delete the record;')">Delete</a></td>
    </tr>
<?php
  }
?>
</table>  -->



