<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/lamia.css"
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


 
 <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">

 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Kwaret</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Gérer les formulaires reçus</a></li>
      <li><a href="#">Gérer les comptes utilisateurs</a></li> 
    </ul>
  </div>
</nav>
 </div>
</nav>
  <ul class="nav navbar-nav navbar-right">
      <li><p>Bienvenue @admin</p></li>
      
    </ul>

        <div class="row" >
        <br>
        </br>
        </div>
 <div>
 	<p> Détails du formulaire reçu </p>
 	<p> Nom du formulaire </p>
 	<p> Catégorie du formulaire </p>
 	<p> Assigner des tags au formulaire </p>
 </div>



 <div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>