<?php

$form = $this->form;
// $form->setAttribute('action',
//                     $this->url('test/default', //your route name ...
//                                array('controller'=>'Profile', 'action' => 'add'))); 

$form->setAttribute('action', $this->url('tags/default', array('controller' => 'Tags', 'action' => 'addTags')));
   // \Zend\Debug\Debug::dump(''); die; 
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formFileSessionProgress();


echo $this->formRow($form->get('value'))."<br></br>";


echo $this->formSubmit($form->get('submit'))."<br></br>";
echo $this->form()->closeTag();
?>

