<h1>tag add</h1>
<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('forms/default', array('controller' => 'Index', 'action' => 'addTag')));
	$form->prepare();

	echo $this->form()->openTag($form);
?>

<div class="form-group">      
	<?php echo $this->formRow($this->form->get('value')); ?>
</div>

<div class="form-group">      
	<?php echo $this->formRow($this->form->get('submit')); ?>
</div>

<?php  echo $this->form()->closeTag(); ?>