<table>
<img src=/img/form1.png class="img-thumbnail" alt="Icone form" width="150" height="200">
<?php
  foreach ($unformulaire as $formulaire) {
?>
  <tr>  
    <td><?php  echo "<strong> Nom formulaire : </strong>".$formulaire['form_name']; ?></td>   
    <td><?php  //echo "<strong> Nom formulaire : </strong>".$form_id['form_id']; ?></td>    
  </tr>
</table>  
  </br>
<?php
  }
?>

</table>
<table>

<a href="<?php echo $this->url('forms/default', array('controller' => 'Index', 
    'action' => 'addCategory'));?>"><?php echo $this->translate('Ajouter une nouvelle categorie'); ?></a>

<h1>les categories</h1>
<?php
  foreach ($categories as $category) {
?>
  <tr>  
    <td><?php  echo $category['id']; ?></td>    
    <td><?php  echo $category['value']; ?></td>   
  </tr>
</table>  
  </br>
<?php
  }
?>
<tr>
  <h2>liste des commentaires de ce formulaire</h2>
</tr>

  </br>

  <?php  echo "<strong>   form_id  : </strong>".$formId ?> 

</br>
_____________________________________________________________________________________________________________________________________________
<h2>Ajouter un nouveau tag</h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('forms/default', array('controller' => 'Index', 'action' => 'addTagForm')));
$form->setData(array('form_id' => $formId));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('form_id'))."<br>";
echo $this->formRow($form->get('value'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
 ?>

 </html>



