<h1>les informations d 'un formulmaire et ses commentaires</h1>
<a href="<?php echo $this->url('forms/default', array('controller' => 'Index', 
    'action' => 'uploadForm'));?>"><?php echo $this->translate('Ajouter un nouveau formulaire'); ?></a>
  </br> 

<img src=/img/form2.png class="img-thumbnail" alt="Icone form" width="150" height="200">
</br>
<tr>  
    <td><?php  echo "<strong>   id du formulaire   : </strong>".$form_id."</br>" ?></td> 
    <td><?php  echo "<strong> Nom formulaire : </strong>".$unformulaire['form_name']."</br>"; ?></td>   
    <td><?php  echo "<strong> category id  : </strong>".$unformulaire['category_id']."</br>"; ?></td>    
</tr>


<h1> Liste des commentaires </h1>
<table>
<?php
  foreach ($comments as $comment) {
?>
  <tr>
      <td><?php  echo $comment['id'].':'; ?></td>   
      <td><?php  echo $comment['value']; ?></td>
      <td> 
        <a href="<?php echo $this->url('forms/default', 
                array('controller' => 'index', 'action' => 'updateComment', 'id' => $comment['id'])); ?>"> 
          <u> Modifier </u>   
        </a>
      </td>
      <td> 
     <?php //var_dump($comment['id']);      die; ?>
      <a href="<?php echo $this->url('forms/default',
        array('controller' => 'index', 'action' => 'deleteComment', 'id' => $comment['id'], $form_id));?>" 
        onclick="return confirm('Do you rely want to delete the record;')"><u> Delete </u> 
      </a>
      </td>
    </br>
  </tr>
</table>  
<?php
  }
?>

</br>

<h1> Les tags de ce formulaire sont </h1>
<tr>
<?php 
$key = 1 ;
            foreach($formtags as $key=>$row){
                $key = $key + 1; ?>
             <tr>
                <td> <?php  echo    'tag_id : <strong> '.($row['tag_id']).'</strong> <br></br>'; ?></td>
                <td> <?php  echo    'tag_value: :<strong> '.($row['value']).'</strong> <br></br>'; ?></td>
                <td> <?php  echo '________________________________________________________________ <br>'; 
              } 
              ?></td> </tr>
</tr>

<br>
</br>
_____________________________________________________________________________________________________________________________________________
<h2>Ajouter un nouveau commentaire</h2>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('forms/default', array('controller' => 'index', 'action' => 'addComment')));
$form->setData(array('form_id' => $form_id));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('form_id'))."<br>";
echo $this->formRow($form->get('value'))."<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
 ?>



