<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="css/custom.css">
 <link rel="stylesheet" href="css/style.css">
</head>
<body>

  <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">
       <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Kwaret</a>
          </div>
          <ul class="nav navbar-nav"> 
              <li class="active">  
            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'index'));?>"><span style="font-size:1.2em; color: #6cbf6c;" class="glyphicon glyphicon-home "></span></a></li>          
       

            <!-- <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
              'action' => 'login'));?>">Se connecter</a></li> -->
            <li><a href="<?php echo $this->url('forms/default', array('controller' => 'index', 
              'action' => 'upload-form'));?>">Uploader un formulaire</a></li>
            <li><a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 
              'action' => 'index'));?>">S'inscrire</a></li>  
            <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'contact'));?>">Contact</a></li>

            </ul></ul>
            <ul class="nav navbar-nav navbar-right">           
             
                <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
                  'action' => 'logout'));?>"><span style="font-size:1.2em; color: #6cbf6c;" class="glyphicon glyphicon-log-in"></span>  Connexion </a></li>
            </ul>            
          </ul>
        </div>
      </nav>
  </div> 
  <!-- fin navbar -->    
<br></br>   <br></br>   <br></br>

<div class="row">
    <div class="contenuFindForm">
      <h2> Détails du formulaire : <u><?php  
           echo $unformulaire['form_name']."</br>"; ?></u>
      </h2><span style="font-size:9.2em; color: #6cbf6c;" class="glyphicon glyphicon-file"></span>
      </br>
         
      <table class="table table-condensed">
        <thead>
          <tr>           
            <th><h4>Liste des commentaires</h4></th>
            <th></th> <th></th>
            <th></th> <th></th>
            <th></th> <th></th>
            <th></th> <th></th> <th></th>
            <th></th> <th></th> <th></th>
          </tr>
        </thead>
        <tbody>            
          <?php   foreach ($comments as $comment) {      ?>
          <tr>
          
          <td></td>   
          <td><?php  echo  $comment['value']; ?></td> 
          <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
          <td>
                <a href="<?php echo $this->url('forms/default', 
                  array('controller' => 'Index', 'action' => 'updateComment', 'id' => $comment['id'])); ?>">                        
                  <span style="font-size:1.4em; color: #6cbf6c;" class="glyphicon glyphicon-edit"></span> 
                </a>      
              
          
              <a href="<?php echo $this->url('forms/default', 
                   array('controller' => 'Index', 'action' => 'deleteComment', 'id' => $comment['id'])); ?>"" 
                   onclick="return confirm('vous voulez confirmer la suppresion de ce formulaire;')"> 
                  <span style="font-size:1.4em; color: #6cbf6c;" class="glyphicon glyphicon-trash"></span> 
                   
              </a>
          </td>
          </tr>            
        </tbody><?php          }        ?>
      </table>

      <h4>Ajouter un nouveau commentaire à ce formulaire</h4>
      <?php
          $form = $this->form;
          $form->setAttribute('action', $this->url('forms/default', array('controller' => 'index', 'action' => 'addComment')));
          $form->setData(array('form_id' => $form_id));
          $form->prepare();

          echo $this->form()->openTag($form);
          echo $this->formRow($form->get('form_id'))."<br>";
          echo $this->formRow($form->get('value'))."<br>";
          echo $this->formSubmit($form->get('submit'));
          echo $this->form()->closeTag();
       ?>

        <div class="row">
          <h4><b> Vous pouvez retrouvez ce formulaire en utilisant ces tags : </b></h4>           
            <?php foreach($formtags as $row){      ?>
                <td> </td>
                <td> <?php  echo '<strong> '.($row['value']).'</strong> '; ?></td>
                      <?php   }       ?>           
        </div>



<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</div>
</div>
</body>
</html>



















<!-- <h1>les informations d 'un formulmaire et ses commentaires</h1>
<a href="<?php echo $this->url('forms/default', array('controller' => 'Index', 
    'action' => 'uploadForm'));?>"><?php echo $this->translate('Ajouter un nouveau formulaire'); ?></a>
</br>  -->





