
<h1> Les formulaire  de ce tag sont </h1>
<tr>
<?php 
$key = 1 ;
            foreach($list as $key=>$row){
                $key = $key + 1; ?>
             <tr>
                <td> <?php  //echo    'tag_id : <strong> '.($row['id']).'</strong> <br></br>'; ?></td>
                <td> <?php  echo    'form_id: :<strong> '.($row['form_id']).'</strong> <br></br>'; ?></td>
                <td> <?php  echo '________________________________________________________________ <br>'; 
              } 
              ?></td> </tr>
</tr>

<br>
</br>
______