<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="css/custom.css">
 <link rel="stylesheet" href="css/style.css">
</head>
<body>

  <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">
       <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Kwaret</a>
          </div>
          <ul class="nav navbar-nav">          
            <li class="active"><a href="<?php echo $this->url('application/default', array('controller' => 'index', 
              'action' => 'index'));?>">Home</a></li>
            <li><a href="#procedure">Procédure</a></li>
            <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
              'action' => 'login'));?>">Se connecter</a></li> 
            <li><a href="<?php echo $this->url('forms/default', array('controller' => 'index', 
              'action' => 'upload-form'));?>">Uploader un formulaire</a></li>
            <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'contact'));?>">Contact</a></li>
          </ul>
        </div>
      </nav>
     </div>

      	<br></br>		<br></br>		<br></br>
	<div class="row">
		<div class="contenu">
			<h4>Résultat de la recherche</h4>
			<th></th>
		<td> <?php  echo '________________________________________________________________ <br>'; ?>
		</td>
			<tr>
			<?php 
			$key = 1 ;
			            foreach($list as $key=>$row){
			                $key = $key + 1; ?>
			             <tr>
			                <td> <?php  //echo    'tag_id : <strong> '.($row['id']).'</strong> <br></br>'; ?></td>
			                <td> <?php  echo    'form_id: :<strong> '.($row['form_id']).'</strong> <br></br>'; ?></td>
			               
			             <?php  } ?> 
			              </tr>
			</tr>
			<br></br> 		
		</div>
    </div>



<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>
