<br>
</br>
<h1> Liste des formulaires</h1>
<?php
  foreach ($list as $b) {
?>
  <tr>
    <td><?php  echo $b['id']; ?></td> 

     


    <a href="<?php echo $this->url('forms/default', 
                array('controller' => 'index', 'action' => 'detail-form', 'id' => $b['id'])); ?>"> <?php  echo $b['form_name']; ?>    
    </a>

    <td><?php  //echo $b['form_name']; ?></td>
    </br>
  </tr>
</table>  
<?php
  }
?>

<br>
</br>
<h1> Liste des categories</h1>
<?php
  foreach ($categories as $a) {
?>
  <tr>
    <td><?php  echo $a['id']; ?></td>   
    <td><?php  echo $a['value']; ?></td>
    </br>
  </tr>
</table>  
<?php
  }
?>



