<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/custom.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


 
 <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">

 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Kwaret</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Procédure</a></li>
      <li><a href="#">S'inscrire</a></li> 
      <li><a href="#">Se connecter</a></li> 
    </ul>
  </div>
</nav>

  </div>
</nav>
<div class="row" >
<br>
</br>
</div>


<div class="jumbotron text-center">

<div class="row">
  <h1>KWARET</h1>
  <p>Plateforme de centralisation de formulaires administratifs Algériens</p>
   <form class="form-inline">
    <input type="Search" class="form-control" size="60" placeholder="Entrez un mot clé" required>
    <button type="button" class="btn btn-danger">Chercher</button>
  </form>
  </div>           
</div>

<div class="row">
<!--liste formulaires -->
  
  <div class="container">
    <h1><center> Les formulaires administratifs </center> </h1>


      <div class="row">
      
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img  src="http://196.203.67.172:8443/concours2016/files/form2-150x150.png" class="maclasse">
              <div class="caption">
              <center>
                <h3>Formulaire 1 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>
        <div class="col-md-4">
        <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" alt="">
              <div class="caption">
              <center>
                <h3>Formulaire 2 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
                  </center>
              </div>

         </div>
         </div>
        <div class="col-md-4">
        <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" alt="">
              <div class="caption">
              <center>
                <h3>Formulaire 3 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>

        </div>
      </div>
      <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="img-responsive">
              <div class="caption">
              <center>
                <h3>Formulaire 4 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
                  </center>
              </div>
          </div>

        </div>
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="img-responsive">
              <div class="caption">
              <center>
                <h3>Formulaire 5 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="maclasse">
              <div class="caption">
              <center>
                <h3>Formulaire 6 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>

      <nav aria-label="...">
  <ul class="pager">
    <li><a href="#">Previous</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</nav>

  </div>



<h1> Liste des fomulaires </h1>
<a href="<?php echo $this->url('forms/default', array('controller' => 'Index', 
    'action' => 'uploadForm'));?>"><?php echo $this->translate('Ajouter un nouveau formulaire'); ?></a>


<table>
<tr>
  <th>id</th>
  <th>Nom formulaire</th>
  <th>formulaire</th>
</tr>
<?php
  foreach ($rowset as $row) {
?>
  <tr>    
    <td><a href="<?php echo $this->url('forms/default', 
           array('controller' => 'index', 'action' => 'detail-form', 'id' => $row['id'])); ?>"><?php  echo $row['form_name'];?>     
       </a>
    </td>

    <td><a href="<?php echo $this->url('forms/default',
      array('controller' => 'index', 'action' => 'delete', 'id' => $row['id']));?>"onclick="return confirm('Do you rely want to delete the record;')">Delete
       </a>
    </td> 
    </br>
  </tr>
</table>  
<?php
  }
?>
<br>
</br>
<h1> Liste des categories</h1>
<?php
  foreach ($categories as $a) {
?>
  <tr>
    <td><?php  echo $a['id']; ?></td>   
    <td><?php  echo $a['value']; ?></td>
    </br>
  </tr>
</table>  
<?php
  }
?>