<?php
echo '<h1>Update d un formulaire pr l ajout de categorie ... </h1>';

$form->prepare();
$form->setAttribute('action', $this->url('forms/default', array('controller' => 'index', 'action' => 'update', 'id' => $id))); 
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formRow($form->get('form_name'))."</br>";
echo $this->formRow($form->get('category_id'))."</br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
//  echo $this->formRow($form->get('state'))."</br>";
// echo $this->formCollection($form);

?>


