

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/custom.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


 
 <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">

 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Kwaret</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Procédure</a></li>
      <li><a href="#">S'inscrire</a></li> 
      <li><a href="#">Se connecter</a></li> 
    </ul>
  </div>
</nav>

  </div>
</nav>
<div class="row" >
<br>
</br>
</div>


<div class="jumbotron text-center">

<div class="row">
  <h1>KWARET</h1>
  <p>Plateforme de centralisation de formulaires administratifs Algériens</p>
   <form class="form-inline">
    <input type="Search" class="form-control" size="60" placeholder="Entrez un mot clé" required>
    <button type="button" class="btn btn-danger">Chercher</button>
  </form>
  </div>           
</div>
 
<!-- <div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Collaborer</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Chercher</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Télécharger</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
  </div>
</div> -->

<!-- <div class="dropdown">
  <button class="btn btn-lg btn-secondary dropdown-toggle dropdown-toggle-split" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Catégories
    <span class="caret"></span>
  </button>
 <ul class="dropdown-menu dropdown-large" aria-labelledby="dropdownMenu1" >
    <li><a href="#">Etat civil </a></li>
    <li><a href="#"> Social </a></li>
    <li><a href="#"> Etudes </a></li>
    <li><a href="#"> Santé </a></li>
    <li><a href="#"> Logement</a></li>
    <li><a href="#"> Travail</a></li>
  </ul>
</div> -->

<div class="row">
<!--liste formulaires -->
  
  <div class="container">
    <h1><center> Les formulaires administratifs </center> </h1>


      <div class="row">
      
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img  src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="maclasse">
              <div class="caption">
              <center>
                <h3>Formulaire 1 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>
        <div class="col-md-4">
        <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" alt="">
              <div class="caption">
              <center>
                <h3>Formulaire 2 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
                  </center>
              </div>

         </div>
         </div>
        <div class="col-md-4">
        <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" alt="">
              <div class="caption">
              <center>
                <h3>Formulaire 3 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>

        </div>
      </div>
      <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="img-responsive">
              <div class="caption">
              <center>
                <h3>Formulaire 4 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
                  </center>
              </div>
          </div>

        </div>
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="img-responsive">
              <div class="caption">
              <center>
                <h3>Formulaire 5 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>
        <div class="col-md-4"> 
          <div class="thumbnail">
              <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" class="maclasse">
              <div class="caption">
              <center>
                <h3>Formulaire 6 </h3>
                  <p><a href="#" class="btn btn-primary" role="button">Afficher</a> </p>
              </center>
              </div>
          </div>

        </div>

      <nav aria-label="...">
  <ul class="pager">
    <li><a href="#">Previous</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</nav>

  </div>
  <!--détail formulaire -->





   <!--  <div class="thumbnail">
      <img src="http://entraide-sociale.com/wp-content/uploads/2013/06/faire-son-dossier-rsa11.png" alt="">
      <div class="caption">
        <h3>Formulaire 1 </h3>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> </p>
      </div>
    </div> -->
</div>

<div class="row" >
<br>
</br>
</div>

<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>

