
<h1>index liste des commentaires</h1>
<a href="<?php echo $this->url('tags/default', array('controller' => 'Index', 
		'action' => 'add'));?>"><?php echo $this->translate('Ajouter un tag'); ?></a>
<table>
<tr>
	<th>id</th>
	<th>value</th>
</tr>
<?php
	foreach ($rowset as $row) {
?>
		<tr>
			<td><?php  echo $row['id']; ?></td>
			<td><?php  echo $row['value']; ?></td>
		</tr>
			
<?php
	}
?>
</table> 
 
