<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="css/custom.css">
 <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">
       <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Kwaret</a>
          </div>
          <ul class="nav navbar-nav">          
            <li class="active"><a href="#">Home</a></li>         
            <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
              'action' => 'login'));?>">Se connecter</a></li>
            <li><a href="<?php echo $this->url('forms/default', array('controller' => 'index', 
              'action' => 'upload-form'));?>">Uploader un formulaire</a></li>
            <li><a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 
              'action' => 'index'));?>">S'inscrire</a></li>  
            <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'contact'));?>">Contact</a></li>
          </ul>
        </div>
      </nav>

  </div> 
  <!-- fin navbar -->


  <div class="row s1"> <br></br><br></br></div>
    <div class="row">
      <div class="jumbotron text-center">
          <h1>Kwaret</h1>      
            <h5>Plateforme de centralisation de formulaires administratifs Algériens</h5>               
      </div>
    </div>   
  </div>
        <br></br>   <br></br>   <br></br>
  <div class="row s1"></div>
  <div class="row">
    <!-- <div class="contenuLogin"> -->
        <div class="row">
           <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <h1 class="page-header text-center">Contactez-nous</h1>
        <form class="form-horizontal" role="form" method="post" action="index.php">
          <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" >
              <!-- <?php echo "<p class='text-danger'>$errName</p>";?> -->
            </div>
          </div>
          <div class="form-group">
            <label for="email" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" >
              <!-- <?php echo "<p class='text-danger'>$errEmail</p>";?> -->
            </div>
          </div>
          <div class="form-group">
            <label for="message" class="col-sm-2 control-label">Message</label>
            <div class="col-sm-10">
              <textarea class="form-control" rows="4" name="message"></textarea>
              <!-- <?php echo "<p class='text-danger'>$errMessage</p>";?> -->
            </div>
          </div>
          <div class="form-group">
            <label for="human" class="col-sm-2 control-label">2 + 3 = ?</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" id="human" name="human" placeholder="Your Answer">
              <!-- <?php echo "<p class='text-danger'>$errHuman</p>";?> -->
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
              <center><input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary"></center>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
             <!--  <?php echo $result; ?>   -->
            </div>
          </div>
        </form> 
      <!-- </div> -->
    </div>
  </div>   

        </div>
    </div>
  </div>

<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>


 


    









