 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/custom.css">
</head>
<body>

  <nav id=mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom affix">
       <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Kwaret</a>
          </div>
          <ul class="nav navbar-nav">          

            <li class="active">  
            <a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'index'));?>"><span style="font-size:1.2em; color: #6cbf6c;" class="glyphicon glyphicon-home "></span></a></li>          

            <!-- <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
              'action' => 'login'));?>">Se connecter</a></li> -->
                <li><a href="#procedure">Procédure</a></li>
            <li><a href="<?php echo $this->url('forms/default', array('controller' => 'index', 
              'action' => 'upload-form'));?>">Uploader un formulaire</a></li>
            <li><a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 
              'action' => 'index'));?>">S'inscrire</a></li>  
            <li><a href="<?php echo $this->url('application/default', array('controller' => 'index', 
                  'action' => 'contact'));?>">Contact</a></li>
            </ul></ul>
            <ul class="nav navbar-nav navbar-right">           
             
                <li><a href="<?php echo $this->url('auth/default', array('controller' => 'index', 
                  'action' => 'logout'));?>"><span style="font-size:1.2em; color: #6cbf6c;" class="glyphicon glyphicon-log-in"></span>  Connexion </a></li>
            </ul>  
          </ul>
        </div>
      </nav>
  </div> 
  <!-- fin navbar -->

  <div class="row s1"> <br></br><br></br></div>
    <div class="row jumbotron text-center">
          <h1>Kwaret</h1>      
            <h5>Plateforme de centralisation de formulaires administratifs Algériens</h5>               
    </div>   
  </div>

  <div class="row jumbotronMiddle">
    <br></br> 
      <div class="container center">   
        <div class="row text-center">         
            <h1> Rechercher un formulaire par mot clé </h1>
             <br></br> 
              <h4> Mot clé </h4>
                    <?php
                          $form = $this->form;
                          $form->setAttribute('action', $this->url('forms/default', array('controller' => 'index',
                           'action' => 'findFormByTag')));        
                          $form->prepare();
                          echo $this->form()->openTag($form); ?>             
                          <?php echo $this->formRow($form->get('value')); ?>                         
                          <?php //echo $this->formRow($form->get('value')); ?>            
                          <?php  echo $this->formSubmit($form->get('submit'));
                          echo $this->form()->closeTag();
                    ?>     
          </div>  
          <div class="row text-center"></div>    
     </div>
  </div>

  <div class="container">          
              <?php    
                  foreach ($categories as $key => $categorie) 
                  {   
              ?>     
             
          <?php }  ?>
  </div> 


 <div class="row jumbotronButtom" id="procedure">
     <center><h1>Procédure Kwaret</h1></center>   
        <div class="media">
            <div class="media-left media-middle"> 
            <br></br><br></br>
                <span style="font-size:15em; color: #6cbf6c;" class="glyphicon glyphicon-file"></span>
            </div>
               
            <div class="media-body">
                <hr>  </hr> <br></br>
                <div class="media-heading left"><h4>Qu'est-ce que Kwaret? Et comment contribuer?</h4>
                    <br></br>
                   <p>Kwaret est une plateforme collaborative de centralisation de formulaires admnistratifs Algériens</p>
                   <p>Elle vise à faire ontribuer les citoyens au <b>partage</b> et à la <b>collaboration</b></p>
                   <p>Pour faciliter le process, KWARET permet à ses utilisateurs de se connecter à la plateforme, pour ajouter directement les formulaires administratifs vierges. 
                   <p>Ainsi, ils seront validés directement via la plateforme . </p>
                   <p>Une fois validés, la mise en ligne est immédiate, et ces formulaires seront accessibles par tous les citoyens en libre téléchargement.
                </div>
            </div>    
        </div>
</div>  

<div class="row">
    <div class="container">
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
</div>

<div class="row">
    <div class="container">
    <p> </p>
</div>


  
  <div class="alt1 padding" id="about">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h2 class="text-center">Past work</h2>
            <p class="text-justify"> malesuada magna mollis euismod. Donec sed odio dui. Donec sed odio dui.malesuada magna mollis euismod. Donec sed odio dui. Donec sed odio dui. </p>
            <a href="#one" class="btn btn-default">Tell me more..</a>
          </div>
          <div class="col-md-4">
            <h2 class="text-center">Past work</h2>
            <p class="text-justify"> Donec sed odio duiagna mollis euismod. Donec sed odio dui.malesuada magna mollis euismod. Donec sed odio dui. Donec sed odio dui. </p>
            <a href="#two" class="btn btn-default">Tell me more..</a>
          </div>
          <div class="col-md-4">
            <h2 class="text-center">Past work</h2>
            <p class="text-justify">sem malesuada magna mollis euismod. Donec sed odio dui.malesuada magna mollis euismod. Donec sed odio dui. Donec sed odio dui. </p>
            <a href="#three" class="btn btn-default">Tell me more..</a>
          </div>
        
        </div>
    </div>  
  </div>


<div id="footer">
  <!-- <div class="container"> -->
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
 <!--   --></div>
</div>
</body>
</html>

