<!DOCTYPE html>
<html lang="en">
<head>
  <title>Kwaret</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" href="css/custom.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


 
 <nav id=mainNav" class="navbar mynav navbar-fixed-top navbar-custom affix">

 <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Kwaret</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="#">Procédure</a></li>
      <li><a href="#">S'inscrire</a></li> 
      <li><a href="#">Se connecter</a></li> 
    </ul>
  </div>
</nav>

  </div>
</nav>
<div class="row" >
<br>
</br>
</div>


<div class="myclass text-center">

<div class="row">
  <h1>KWARET</h1>
  <p>Plateforme de centralisation de formulaires administratifs Algériens</p>
   <form class="form-inline">
    <input type="Search" class="form-control" size="60" placeholder="Entrez un mot clé" required>
    <button type="button" class="btn btn-danger">Chercher</button>
  </form>
  </div>           
</div>
 
<!-- <div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>Collaborer</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Chercher</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
    <div class="col-sm-4">
      <h3>Télécharger</h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
    </div>
  </div>
</div> -->
<div>

    




<center><h2>Procédure</h2></center>
<hr></hr>

</div>

<div class="container marketing" >
    <div class="row">
        <div class="col-lg-4">
            
            <img class="myclass2" class="pull-right"  src="img/Programming-Search-Property-icon.png">
            <div class="right">
            <center><h2> Plateforme collaborative </br>
                    de partage de formulaires administratifs Algériens</h2>
            <p>Pour faciliter le process,</p>
            <p> KWARET permet à ses utilisateurs de se connecter à la plateforme, pour ajouter directement les formulaires administratifs vierges.</p> 
            <p>Ainsi, ils seront validés directement via la plateforme. </p>
            <p>Une fois validés, la mise en ligne est immédiate, et ces formulaires seront accessibles par tous les citoyens en libre téléchargement. </p>
            </center>
            </div>

     
    </div>
</div>

<form class="form-inline">
    <input type="Search" class="form-control" size="60" placeholder="Entrez la catégorie du formulaire" required>
    <button type="button" class="btn btn-danger">Chercher</button>
  </form>
<br>
</br>

  <div>
    <div class="dropdown">
      <button class="mybtn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Sélectionner le formulaire par catégorie
        <span class="mycaret"> </span>
      </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                      <li><a href="#">Etat civil </a></li>
                      <li><a href="#"> Social </a></li>
                      <li><a href="#"> Etudes </a></li>
                      <li><a href="#"> Santé </a></li>
                      <li><a href="#"> Logement</a></li>
                      <li><a href="#"> Travail</a></li>
                    </ul>
    </div>
</div>

  </div>

<div class="row">
    <div class="container">
    <p>&nbsp;</p>
</div>

<div class="row">
    <div class="container">
    <p> </p>
</div>

<!-- <div>
 <footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the WEB</h3>
                </div>
                <div class="footer-col col-md-4">
                <h3> About Kwaret </h3>
                </div>
            </div>

        </div>
    </div>
               
 </footer>
</div> -->
<div class="row" >
<br>
</br>
</div>

<div id="footer">
  <div class="container">
    <p>&nbsp;</p>
    <center><p class="lead">All rights reserved @<a href="">Kwaret.com</a></p></center>
  </div>
</div>

</body>
</html>